import {Layout} from "@/components/Layout/Layout";
import {description} from "@/assets/mocks/description";
import {dataHome} from "@/assets/mocks/homePageData";
import { DescriptionList } from "@/components/DescriptionList/DescriptionList";
import Head from "next/head";

const About = () => (
    <>
      <Head>
        <title>Компания Высота Шатура - о нас</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataHome}/>
      <DescriptionList
        title={description.home.about.title}
        alt={description.home.about.title}
        img={description.home.about.image}
      />
    </>
)

export default About;