import {Layout} from "@/shared/Layout/Layout";
import {description} from "@/assets/mocks/description";
import {dataHome} from "@/assets/mocks/homePageData";
import { PageBody } from "@/shared/PageBody/PageBody";
import Head from "next/head";

const Actions = () => (
    <>
      <Head>
        <title>Акции компании - акции на натяжные потолки, акции на окна, акции на жалюзи</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataHome}/>
      {/*<PageBody data={description.home.promotions}/>*/}
    </>
)

export default Actions;