import {Layout} from "@/shared/Layout/Layout";
import { PageBody } from "@/shared/PageBody/PageBody";
import {dataCeilings} from "@/assets/mocks/ceilingsPageData";
import Head from "next/head";

const Ceilings = () => (
    <>
      <Head>
        <title>
          Натяжные потолки. Компания Высота предлагает качественный монтаж натяжных потолков.
          Отличные цены на натяжные потолки! Установка потолков в срок - быстрый и чистый монтаж, опытные монтажники.
          Установим натяжные потолки любой сложности!
          Комплектующие для натяжных потолков и полотна
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataCeilings.links} />
      <PageBody data={dataCeilings.data}/>
    </>
);

export default Ceilings;