import Head from 'next/head';
import {dataHome} from "@/assets/mocks/homePageData";
import {Layout} from "@/components/Layout/Layout";
import {BackgroundImage} from "@/components/BackgroundImage/BackgroundImage";

const Home = () => (
    <>
      <Head>
        <title>Натяжные потолки, окна ПВХ, жалюзи, рольставни. Компания Высота Шатура</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataHome} />
      <BackgroundImage alt="homePage" src="https://www.luxe-potolok.ru/o/primer/v-studiyu-2.jpg" />
    </>
);

export default Home;

