import {Layout} from "@/shared/Layout/Layout";
import {description} from "@/assets/mocks/description";
import {dataHome} from "@/assets/mocks/homePageData";
import { WorksPrice } from "@/assets/mocks/worksPrice";
import { WorkPrice } from "@/shared/WorkPrice/WorkPrice";
import Head from "next/head";

const OurWorks = () => (
    <>
      <Head>
        <title>Примеры работ компания Высота</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataHome}/>
      <WorkPrice servicesMap={WorksPrice}  titleH2={description.home.ourWorks.title.toString()}/>
    </>
)

export default OurWorks;