import {Layout} from "@/components/Layout/Layout";
import {dataHome} from "@/assets/mocks/homePageData";
import Head from "next/head";

const Reviews = () => (
    <>
      <Head>
        <title>Компания Высота - отзывы о компании Высота</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
        <Layout data={dataHome}/>
    </>
)

export default Reviews;