import Head from 'next/head';
import {dataHome} from "@/assets/mocks/homePageData";
import {Layout} from "@/components/Layout/Layout";
import {BackgroundImage} from "@/components/BackgroundImage/BackgroundImage";
import { ProductPage } from "@/components/ProductPage/ProductPage";
import { WallsContent } from "@/components/WallsContent/WallsContent";

const Home = () => (
  <>
    <Head>
      <title>Тихие стены. Аккустический комфорт. Натяжные потолки, окна ПВХ, жалюзи, рольставни. Компания Высота Шатура</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logoTop.png" />
    </Head>
    <Layout />
    <WallsContent />
  </>
);

export default Home;