import { Layout } from "@/shared/Layout/Layout";
import { PageBody } from "@/shared/PageBody/PageBody";
import { dataWindows } from "@/assets/mocks/windowsPageData";
import Head from "next/head";


const Windows = () => (
    <>
      <Head>
        <title>Окна ПВХ с качественной установкой от компании Высота. Пластиковые окна. Монтаж окон</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoTop.png" />
      </Head>
      <Layout data={dataWindows.links}/>
      <PageBody data={dataWindows.data}/>
    </>
);

export default Windows;